use_frameworks!

platform :ios, '8.0'

target 'FKFBPodLib_Example' do
  pod 'FKFBPodLib', :path => '../'

  target 'FKFBPodLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
